/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


<script>
            $(function () {
                var availableTags = [
                    "A Combined Method for Mitigating Sparsity Problem in Tag  Recommendation",
                    "A Design Science Approach to Collective Intelligence Systems",
                    "A Guiding Framework for Ontology Reuse in the Biomedical Domain",
                    "A Model-Driven Development of Web Applications  Using AngularJS Framework",
                    "A Pervasive Mobile Assistance System for Health and Fitness Scenarios",
                    "A PRACTICAL GUIDE TO DATA  STRUCTURES AND ALGORITHMS  USING JAVA",
                    "A Semantic Knowledgebase Representation of  Geospatial Data in the Context of Bangladesh",
                    "A Semantic Web Primer second edition",
                    "A Similarity Measuring Service for SNOMED-CT (Structural analysis of concepts in ontology)",
                    "A survey of RDF store solutions",
                    "A Virtual Imaging Platform for Multi-Modality Medical Image Simulation",
                    "A Web Base Android Application Development System",
                    "A Web-based Smart Inference System to Support Automated Generation of  LCA Simulation Models",
                    "Agent-Based Semantic Web Service Composition",
                    "An Extensible Description Language for Video Games",
                    "An Introduction to Information Retrieval",
                    "An Ontology-based Annotation of Cardiac  Implantable Electronic Devices to Detect  Therapy Changes in a National Registry",
                    "An Ontology-based Information Extraction (OBIE) Framework for Analyzing  Initial Public Offering (IPO) Prospectus",
                    "Android Essentials",
                    "Applied Semantic Web Technologies",
                    "ASeCS: Assistive Self-Care Software Architectures   for Delivering Service in Care Homes",
                    "Automating the Integration of Clinical Studies into Medical Ontologies",
                    "Automation System Using DNP3.0 in Smart Grid",
                    "Building a core biomedical knowledge base",
                    "Clustered and Smarter Web mining using Semantic Web",
                    "Connected Smart Cities: Interoperability with SEG 3.0 for the Internet of Things",
                    "Constructing a Global Social Service Network  for Better Quality of Web Service Discovery",
                    "Curating A Semantic Bibliographic Catalog",
                    "Determining Semantically Related Signi?cant Genes",
                    "Do Ontological Guidelines Improve Understandability of Conceptual Models?  A Meta-Analysis of Empirical Work",
                    "Electronic  Commerce Meets  the Semantic Web",
                    "Facelets Essentials: Guide to JavaServer™ Faces View  Definition Framework",
                    "Foundations of Semantic Web Technologies",
                    "Fundamentals of Computer Science Using Java",
                    "How to Successfully Establishing Online Stores?",
                    "INFORMATION RETRIEVAL  SYSTEMS:  Theory and Implementation ",
                    "Introduction  to Android™  Application  Development (Fourth Edition)",
                    "Introduction to Information Retrieval",
                    "Introduction to IT Architectures and Applications in Healthcare  Environments Minitrack ",
                    "Introduction to Microprocessors and Microcontrollers",
                    "Introduction to the Semantic Web  and Semantic Web Services",
                    "Introduction to Theories in IS Research Minitrack",
                    "Learn Java For Web Development",
                    "Mastering Structured Data On The Semantic Web",
                    "Microcontrollers: From  Assembly Language to C Using the PIC24 Family",
                    "Modeling and Generating Graphical User Interface  for MVC Rich Internet Application using a Model  Driven Approach",
                    "Modeling Semantic Web Services",
                    "ONTOLOGY AND THE SEMANTIC WEB",
                    "Ontology Management Semantic Web, Semantic Web Services And Business Applications",
                    "PBNA: An Improved Probabilistic Biological Network Alignment Method",
                    "Piecemeal Development of Intelligent Applications for Smart Spaces",
                    "Pivot: Fast, Synchronous Mashup Isolation Using Generator Chains",
                    "Pro Android 2",
                    "Programming the Semantic Web",
                    "Providing a Source Code Security Analysis Model  Using Semantic Web Techniques",
                    "Representing Service Business Models with the Service Business Model  Canvas - The Case of a Mobile Payment Service in the Retail Industry",
                    "RGFinder: A System for Determining  Semantically Related Genes using GO Graph  Minimum Spanning Tree",
                    "Search Engines Information Retrieval in Practice",
                    "Semantic Link Network-Based Model for Organizing Multimedia Big Data",
                    "Semantic Mashups - Intelligent Reuse of Web Resources",
                    "Semantic Representations of Actors and Resource Allocation through  Reasoning in Humanitarian Crises",
                    "Semantic Web  And Model-Driven  Engineering",
                    "Semantic Web And Ontology",
                    "Semantic Web for Business: Cases and Applications",
                    "Semantic Web For The Working Ontologist Modeling In RDF, RDFS And OWL",
                    "Semantic Web Programming",
                    "Semantic Web Services - Advancement through Evaluation",
                    "Semantic Web Services: Theory, Tools, and Applications",
                    "Semantic Web: Concepts, Technologies and Applications",
                    "Semantic Web-Based  Information Systems: State-of-the-Art Applications",
                    "Semantics-Based Composition of Factory Automation Processes Encapsulated by Web Services",
                    "SemanticWeb Technologies Trends and Research in Ontology-based Systems",
                    "SMARTSPACE: Multiagent Based Distributed Platform for Semantic Service Discovery",
                    "The CoAP-based M2M Gateway for Distribution",
                    "The Semantic Web: A Guide to the Future of XML, Web Services, and Knowledge Management",
                    "The Unified Modeling Language Reference Manual Second Edition",
                    "Theory Identity: A Machine-Learning Approach",
                    "Twitter  to  Integrate  Human  and  Smart  Objects  by  a",
                    "Value-sensitive Hybrid Information Flow Control for a JavaScript-like Language",
                    "Web  of Things  Architecture",
                    "X86 Assembly Language and C Fundamentals"
                ];
                $("#tags").autocomplete({
                    source: availableTags
                });
            });
        </script>